export const ADD_GOODS_TO_CART = 'addGoodsToCart'
export const MINUS_GOODS_FROM_CART = 'minusGoodsFromCart'
export const SET_GOODS_COUNT = 'setGoodsCount'
export const CLEAR_CART = 'clearCart'
export const SHARE_CART_ELEMENT = 'shareCartElement'
